### ISSUE TITLE
Already existing MX record

### ISSUE THREAD

**Issue by amjad489** [go-gandi/terraform-provider-gandi#126]
Hi,

I'm trying to create all the **`gandi`** DNS records which were manually created by someone else. Till now I was able to create all the existing **`A`**, **`CNAME`**, **`TXT`** records successfully(which were already existing in gandi DNS) to terraform without any issues. 

However i'm having an issue with **`MX`** records where in it says that the record already exists.
```
Error: StatusCode: 409 ; Err: 409: This record already exists 
│ 
│   with gandi_livedns_record.mx_dns_record["@"],
│   on main.tf line 29, in resource "gandi_livedns_record" "mx_dns_record":
│   29: resource "gandi_livedns_record" "mx_dns_record" {
```

i'm assuming this can be similar issue like this https://github.com/go-gandi/terraform-provider-gandi/issues/106

_`provider version`_: **`2.1.0`**

Please advice

**Comment by nlewo** [comment]
@amjad489 do you `terraform import` these resources?

**Comment by amjad489** [comment]
hi @nlewo no, i added all the records to locals file and did terraform apply. all went through except the `MX`
```
resource "gandi_livedns_record" "cname_dns_record" {
  for_each = local.cname
  zone     = each.value.domain
  name     = each.key
  type     = "CNAME"
  ttl      = each.value.ttl
  values   = [each.value.value]
}

resource "gandi_livedns_record" "a_dns_record" {
  for_each = local.a
  zone     = each.value.domain
  name     = each.key
  type     = "A"
  ttl      = each.value.ttl
  values   = [each.value.value]
}


resource "gandi_livedns_record" "txt_dns_record" {
  for_each = local.txt
  zone     = each.value.domain
  name     = each.key
  type     = "TXT"
  ttl      = each.value.ttl
  values   = each.value.value
}

resource "gandi_livedns_record" "mx_dns_record" {
  for_each = local.mx
  zone     = each.value.domain
  name     = each.key
  type     = "MX"
  ttl      = each.value.ttl
  values   = each.value.value
}
```

**Comment by nlewo** [comment]
If a resource already exists in the API, you should then have to define it in your Terraform configuration file and then run `terraform import` to populate the Terraform state. Once imported, you could then run `apply`.

See https://learn.hashicorp.com/tutorials/terraform/state-import?in=terraform%2Fstate for more details.

**Comment by amjad489** [comment]
yeah to make it working that's what i did
