### ISSUE TITLE
Move to an org?

### ISSUE THREAD

**Issue by thommay** [go-gandi/terraform-provider-gandi#45]
@tiramiseb I think we should move the terraform provider and the api to an org ( `go-gandi`?). That way we can easily publish the terraform provider to hashicorp.

**Comment by tiramiseb** [comment]
Yes, you are right. I'm doing it right now.

**Comment by tiramiseb** [comment]
There it is, an organization ! :wink: 
I have changed repositories addresses in `*.go` and `go.mod` files, but I'm not sure it is enough. Don't hesitate to make any other necessary change.

I'm going to make a PR on the terraform doc to change the repository address in the community providers page.

**Comment by thommay** [comment]
@tiramiseb thanks! Would you mind making me an owner?

**Comment by tiramiseb** [comment]
done :slightly_smiling_face:
