### ISSUE TITLE
Preparing for 2.0.0

### ISSUE THREAD

**Issue by thommay** [go-gandi/terraform-provider-gandi#48]
The intent is to publish 2.0.0 to the Terraform registry (#47):

- [x] Check with Gandi that they're happy we're doing this
- [x] [Document the provider](https://www.terraform.io/docs/registry/providers/docs.html) (see #77 )
- [x] [Create a GPG key](https://www.terraform.io/docs/registry/providers/publishing.html#preparing-and-adding-a-signing-key)
- [x] [Register GPG key with Terraform Registry](https://www.terraform.io/docs/registry/providers/publishing.html#organizations)
- [x] Release go-gandi
- [ ] Fix GitHub Actions for releases
- [ ] Publish!

**Comment by thommay** [comment]
@baloo any idea who we might contact at Gandi to check that it's ok to publish this to the terraform registry? 
Also, I asked a while ago about whether y'all had a sandbox for testing API libraries (and this provider) - did anything happen there?

**Comment by gizero** [comment]
Any news on this? We currently pull from @manvalls published fork but there's an annoying issue with file permissions (mentioning here, because of disabled issues on the fork) after the provider is pulled. Would be nice to work to fix all of this upstream, which means here, if I'm not missing something obvious.

**Comment by manvalls** [comment]
Sorry, I build - and use - the provider on Windows, hence the file permissions issue. I'll try to fix it later on today.

**Comment by gizero** [comment]
@manvalls Thanks for fixing the file permission issue on your latest release (and sorry for hijacking this issue again..)
@thommay Any plans to move forward with releasing on Terraform registry from this project? Looks like yours is the upstream for some forks which have already been published, but I believe we should convey efforts to maintain an "official" release. What's your opinion?

**Comment by tiramiseb** [comment]
Hello,

As the original developer (but not using Terraform these days), I think the same, we have created the go-gandi group precisely to maintain "official" releases (even if we are not Gandi employees)...

**Comment by lyda** [comment]
Would it be useful for customers to ask for official blessing for this?

**Comment by pichouk** [comment]
Hi, any news on this ? Do you think that this (great and useful) provider will be pushed to Terraform Registry one day ? Or still be maintained like before, without using the registry ?

**Comment by taoufik07** [comment]
@tiramiseb @thommay I've pushed changes to fix the release via #72 and created this issue #71 to track versioning, can you take a look and release a version with the latest changes so we can avoid always building master?

**Comment by b-enoit-be** [comment]
I would really love to see this repository ending in terraform provider too, also because, by holding it, we ended in a non-sensical situation where we have five different gandi providers [listed in the registry](https://registry.terraform.io/search/providers?q=gandi), where all of them are forks of this repository, some of them up to date, some of them dozen of commits behind.

**Comment by yanndinendal** [comment]
> Also, I asked a while ago about whether y'all had a sandbox for testing API libraries (and this provider) - did anything happen there?

Hi, you will be happy to hear that there is now a sandbox available for the v5 API:  
https://api.gandi.net/docs/reference/#Sandbox-API :)

**Comment by nlewo** [comment]
And since few days, the provider can takes an `url` parameter allowing to easily switch to the Sandbox API!

**Comment by nlewo** [comment]
FYI, i pushed a PR to regenerate the documentation #77 (accordingly to the Terraform documentation).

**Comment by nlewo** [comment]
@tiramiseb I'm volunteer to publish a release. 
It would however be much more simple with accesses to GitHub secrets and webhooks of this repository.
Would you be ok to give me such permissions?

**Comment by nlewo** [comment]
@tiramiseb I unfortunately don't have enough power (i can't see the tab "Settings").
Otherwise, we could pair for the releasing process.

**Comment by nlewo** [comment]
@tiramiseb I added the todo items "Release go-gandi" in this ticket description.

And thx for powers!

**Comment by nlewo** [comment]
The v2.0.0 has been published!

https://registry.terraform.io/providers/go-gandi/gandi/latest

Thank you all!
